runtime: go111
main: gae-fe

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: gae-fe/public/favicon.ico

  - url: /static
    static_dir: gae-fe/public

  - url: /
    static_files: gae-fe/public/index.html
    upload: gae-fe/public/index.html

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
