// Code generated by "stringer -type=key"; DO NOT EDIT.

package eridanus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[serverKey-0]
}

const _key_name = "serverKey"

var _key_index = [...]uint8{0, 9}

func (i key) String() string {
	if i < 0 || i >= key(len(_key_index)-1) {
		return "key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _key_name[_key_index[i]:_key_index[i+1]]
}
