// Code generated by "stringer -type=StringMatcherType"; DO NOT EDIT.

package eridanus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Exact-0]
	_ = x[Regex-1]
}

const _StringMatcherType_name = "ExactRegex"

var _StringMatcherType_index = [...]uint8{0, 5, 10}

func (i StringMatcherType) String() string {
	if i < 0 || i >= StringMatcherType(len(_StringMatcherType_index)-1) {
		return "StringMatcherType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StringMatcherType_name[_StringMatcherType_index[i]:_StringMatcherType_index[i+1]]
}
