// Code generated by "stringer -type=URLClassifierType"; DO NOT EDIT.

package eridanus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[File-0]
	_ = x[Post-1]
	_ = x[List-2]
	_ = x[Watch-3]
}

const _URLClassifierType_name = "FilePostListWatch"

var _URLClassifierType_index = [...]uint8{0, 4, 8, 12, 17}

func (i URLClassifierType) String() string {
	if i < 0 || i >= URLClassifierType(len(_URLClassifierType_index)-1) {
		return "URLClassifierType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _URLClassifierType_name[_URLClassifierType_index[i]:_URLClassifierType_index[i+1]]
}
